# coding: utf-8

"""
    DBMS API

    DBMS API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI
from starlette.middleware.cors import CORSMiddleware

from .apis.default_api import router as DefaultApiRouter
from .database.sql_alchemy import BaseORMModel, engine

BaseORMModel.metadata.create_all(bind=engine)


app = FastAPI(
    title="DBMS API",
    description="DBMS API",
    version="1.0.0",
)


origins = [
    "http://localhost:3000",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(DefaultApiRouter)
